CREATE TABLE [dbo].[Gift]
(
	[Id] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[IdeaId] BIGINT NULL FOREIGN KEY REFERENCES [Idea](Id),
	[Name] NVARCHAR(255) NOT NULL,
	[Price] DECIMAL(9,2) NULL,
	[Where] NVARCHAR(MAX) NULL,
	[AddedBy] BIGINT NOT NULL REFERENCES [User](Id)
)
