CREATE TABLE [dbo].[IdeaGrantee]
(
	[Id] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[IdeaId] BIGINT NOT NULL FOREIGN KEY REFERENCES [Idea](Id),
	[GranteeId] BIGINT NOT NULL FOREIGN KEY REFERENCES [Grantee](Id)
)
