CREATE TABLE [dbo].[IdeaOccasion]
(
	[Id] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[IdeaId] BIGINT NOT NULL FOREIGN KEY REFERENCES [Idea](Id),
	[OccasionId] BIGINT NOT NULL FOREIGN KEY REFERENCES [Occasion](Id)
)
