CREATE TABLE [dbo].[Idea]
(
	[Id] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(MAX) NULL,
	[DateCreated] DATETIME NOT NULL,
	[Tags] NVARCHAR(MAX) NULL,
	[ImageUrl] NVARCHAR(MAX) NULL,
	[UserId] BIGINT NULL FOREIGN KEY REFERENCES [User](Id),
	[IsApproved] BIT NOT NULL, 
	[WhereToBuy] NVARCHAR(MAX) NULL
)
