CREATE TABLE [dbo].[IdeaForEvent]
(
	[Id] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[IdeaId] BIGINT NULL FOREIGN KEY REFERENCES [Idea](Id),
	[EventId] BIGINT NULL FOREIGN KEY REFERENCES [Event](Id)
)
