CREATE TABLE [dbo].[User]
(
	[Id] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[FirstName] NVARCHAR(255) NOT NULL,
	[LastName] NVARCHAR(255) NOT NULL,
	[Username] NVARCHAR(255) NOT NULL UNIQUE,
	[Email] NVARCHAR(255) NOT NULL UNIQUE,
	[PasswordHash] NVARCHAR(255) NOT NULL 
)
